name: Deployment
on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create changelog for Release
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "changelog.config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.github_release.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'rc') }}

  deploy:
    needs: [release]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build electron
        run: |
          npm i
          npm run electron:build

      - name: Cleanup electron dist
        working-directory: dist_electron
        run: |
          ${{ fromJSON('["rm -rf linux-unpacked mac builder-debug.yml bundled", "rm -r -fo win-unpacked, builder-debug.yml, bundled"]')[matrix.os == 'windows-latest'] }}
          ls -l ./

      - name: Upload artifacts to Release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist_electron/*"]'

      - name: Upload artifacts to Google Cloud Storage
        if: secrets.GCP_SA_KEY && secrets.GCS_BUCKET
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          path: dist_electron
          parent: false
          destination: ${{GCS_BUCKET}}
